### ISSUE TITLE
RuntimeError:set_storge is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by ZMD177** [thunlp/Chinese_NRE#23]
Traceback (most recent call last):
  File "D:/pycharm/work/Chinese_NRE-master/main.py", line 187, in <module>
    train(data, configure.savemodel)
  File "D:/pycharm/work/Chinese_NRE-master/main.py", line 97, in train
    model = MGLattice_model(data)
  File "D:\pycharm\work\Chinese_NRE-master\nn\framework.py", line 15, in __init__
    self.encoder = BiLstmEncoder(data)
  File "D:\pycharm\work\Chinese_NRE-master\nn\encoder.py", line 98, in __init__
    self.forward_lstm = LatticeLSTM(lstm_input, lstm_hidden, data.gaz_dropout, data.gaz_alphabet.size(), data.gaz_emb_dim, data.pretrain_gaz_embedding, True, data.HP_fix_gaz_emb, self.gpu)
  File "D:\pycharm\work\Chinese_NRE-master\nn\mglattice.py", line 262, in __init__
    self.rnn = MultiInputLSTMCell(input_dim, hidden_dim)
  File "D:\pycharm\work\Chinese_NRE-master\nn\mglattice.py", line 163, in __init__
    self.reset_parameters()
  File "D:\pycharm\work\Chinese_NRE-master\nn\mglattice.py", line 174, in reset_parameters
    self.weight_hh.data.set_(weight_hh_data)
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

**Comment by zhangluoli** [comment]
请问你把这个问题解决了吗

**Comment by civugd** [comment]
可能是pytorch版本太高，这里需要的版本是0.4.1
对于pytorch1.8版本，可以将所有的
```
x.data.set_(y)
```
替换成
```
with torch.no_grad():
	x.set_(y)
```
